# .goreleaser.yaml
version: 2

project_name: procio

builds:
  - skip: true # We are a library, no binaries needed

release:
  github:
    owner: aretw0
    name: procio
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refactor:"
      - "^style:"
      - "^Merge pull request"
      - "^Merge branch"
  groups:
    - title: Features
      regexp: "^.*feat((\\([\\w\\-\\.]+\\))?):"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix((\\([\\w\\-\\.]+\\))?):"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf((\\([\\w\\-\\.]+\\))?):"
      order: 2
    - title: "Deprecated"
      regexp: "^.*deprecate((\\([\\w\\-\\.]+\\))?):"
      order: 3
    - title: "Others"
      order: 999
